# fly.toml app configuration file generated for data-marios on 2023-08-04T15:50:52+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "data-marios"
primary_region = "nrt"

[build]
dockerfile = "Dockerfile"

# https://fly.io/docs/reference/configuration/#specify-docker-build-arguments
[build.args]
VER="0.0.1"

[http_service]
  internal_port = 9876
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]
